# $schema: https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

linters:
  enable:
    - gosec
    - revive

  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
        - fmt.Fprintf(*text/tabwriter.Writer)
        - fmt.Fprintln(net/http.ResponseWriter)
