issues:
  exclude-use-default: false

linters:
  enable:
    - revive

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
      - fmt.Fprintf(*text/tabwriter.Writer)
      - fmt.Fprintln(net/http.ResponseWriter)
